version: 2

mkdocs:
  configuration: mkdocs.yml

python:
  version: 3.12
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

build:
  os: ubuntu-22-04
  tools:
    python: "3.12"
